project_id = "goclbjumhryxqcumbbak"

[functions.generate-requirements]
verify_jwt = true

[functions.parse-legal-pdf]
verify_jwt = true

[functions.generate-embeddings]
verify_jwt = true

[functions.ask-legal-question]
verify_jwt = true
